"""Models package：统一导出实体。"""
from app.models.models import (
    AdminAlert,
    AiCostLog,
    Coupon,
    CouponRedemption,
    DailyReport,
    DeliverableFile,
    DiagnosisTask,
    Favorite,
    FunnelEvent,
    GameScore,
    InviteRelation,
    Notification,
    NotifySetting,
    Order,
    Package,
    PaymentRecord,
    RiskEvent,
    ShareCard,
    ShareEvent,
    ShareReport,
    TalkTopic,
    User,
)

__all__ = [
    "User",
    "Order",
    "Package",
    "DeliverableFile",
    "DiagnosisTask",
    "Favorite",
    "GameScore",
    "InviteRelation",
    "Notification",
    "NotifySetting",
    "PaymentRecord",
    "ShareCard",
    "ShareEvent",
    "Coupon",
    "CouponRedemption",
    "RiskEvent",
    # V5.0 新增
    "AiCostLog",
    "TalkTopic",
    "ShareReport",
    "FunnelEvent",
    "DailyReport",
    "AdminAlert",
]
